project_name: k3s

resources:
  ram: "10G"
  cpus: "6"
  baseimage_size: "+40G"
  disksize: "200G"

vm:
  directory: ./vm/
  bridge_name: "br0"
  interface: "eth1"
  tap_interface: "tap0"

ports:
  grafana: 3000
  promtail: 31059
  petstore: 30080
  prometheus: 30900
  argocd: 8443

services:
  - name: ssh
    host_port: 8022
    vm_port: 22
  - name: argocd
    host_port: 8443
    vm_port: 8443
  - name: api
    host_port: 9090
    vm_port: 9090
  - name: petstore
    host_port: 30080
    vm_port: 30080
  - name: grafana
    host_port: 3000
    vm_port: 3000
  - name: kubernetes
    host_port: 6443
    vm_port: 6443
  - name: jaeger
    host_port: 16686
    vm_port: 16686
  - name: prometheus
    host_port: 30900
    vm_port: 30900
