project_name: k3s
ram: "10G"
cpus: "6"
services:
  - name: ssh
    host: 8022   
    vm: 22
  - name: 9090
    host: 9090
    vm: 9090
  - name: petstore
    host: 8080   
    vm: 30080
  - name: grafana
    host: 3000   
    vm: 3000
  - name: 6443
    host: 6443
    vm: 6443
  - name: jaeger
    host: 16686   
    vm: 16686
vm_dir: ./vm/
bridge_name: "br0"
disksize: "200G"
interface: "eth1"
tapinterface: "tap0"
