#cloud-config
# network:
#   version: 2
#   ethernets:
#     eth0:
#       dhcp4: true
#       match:
#         macaddress: "52:54:00:12:34:56"
#       set-name: eth0

# #cloud-config
# bootcmd:
#   - echo $INSTANCE_ID > /hello.txt

users:
  - name: user
    lock_passwd: false
    passwd: "$y$j9T$ybdjFbChrTwxHVcMWteJZ1$wRZJ2osGXMnzY1uQ3cN1EdEEMef2qM.3XwSvUPS8Hq6"
    shell: /bin/bash
    ssh_authorized_keys:
      - ssh-rsa AAAAB3NzaC1yc2EAAAADAQABAAACAQDZgBuA47ycWCP1GGw2ApW4VeTWHBDjddw84w4GLP39KX6fxxq7JXEwmkrCMluYfIjT307WF/2Bi63eLEAakPJOppU4bs6i8bdJfve8DbBBqWwHTLqKMu9RSF8+Ff1s6GzZDsjMzFcFyVghjs2TY4TDtTVGnBz+5DIllKNpW0cCPIjcKyG6AB5Arb09YAX7e9t6eoknQWKnrY401kpKWrrfiNpI/sJ9F+AhSQi8A0gMveqgwNob0bxnWDtNOaukoXrgiuED0WjZFkBiHle4HRI3g4/xJh3nsuW/62fdVn+5ry3fnMjZy1YIbo2RnDLvfAzgOkowC04TRYITIsofZ5vLKV8JhqjiLBU1t+jJk2VurVk1i+CO/E2H52MpprqWTyBdZNPgpVYj6Rq/QKm3elOn+psTHAz1VE/0Td3QRoQ8Qv1Fzst6eRlfjbm7mP1ucyTIlU496MunS2ABbnCtoyVTekDqHsKAk/cWxBQavxnBIzTEbnVr2A4Ol32awyPkzTbcsw+j7PaZSKIgisAv0YD8l5WqpZ6CU1o+hcaMVoxn7JG7EwWiX7hL+hC+9f4VEXVtWPAv3ru9CZqdzMlneKRbIq+yJymXABvtuLmavbEp1GDldntXqBS6ZbgqWwDIf1b55FgRHglo9AP+EZgvYPFPInwmh+dqiwy3wWrtm8uerQ== master@localhost -p 5253, suse
      - ssh-ed25519 AAAAC3NzaC1lZDI1NTE5AAAAIBQqNkSM5vQOZDxCY6DWBIqQi1+0J/xHtGCms/lF3ENO andrey@xmg.lan
    sudo: ALL=(ALL) NOPASSWD:ALL

ssh_pwauth: false
package_update: true
package_upgrade: true

apt:
  sources:
    docker.list:
      source: deb [arch=amd64] https://download.docker.com/linux/ubuntu $RELEASE stable
      keyid: 9DC858229FC7DD38854AE2D88D81803C0EBFCD88

packages:
  - openssh-server
  - curl
  - nmap 
  - ansible 
  - golang-go
  - python3-pip
  - ca-certificates
  - docker-ce
  - docker-ce-cli

runcmd:
  # SSH setup
  - [ systemctl, enable, ssh ]
  - [ systemctl, start, ssh ]
  # Mount CD-ROM with resources
  - 'sudo mount /dev/cdrom /mnt || exit 1'

  - 'bash /mnt/scripts/helm_setup.sh || exit 1'
  - 'bash /mnt/scripts/ansible_deployment.sh || exit 1'
  - 'sudo -i -u user bash /mnt/scripts/rook_ceph_install.sh || exit 1'
  - 'sudo -i -u user bash /mnt/scripts/monitoring_tools_setup.sh || exit 1'
  - 'sudo -i -u user bash /mnt/scripts/swagger_petstore_setup.sh || exit 1'
  - 'sudo -i -u user bash /mnt/scripts/promtail_setup.sh || exit 1'
  - 'sudo -i -u user bash /mnt/scripts/argocd_setup.sh || exit 1'
  - 'sudo -i -u user bash /mnt/scripts/final_verification.sh'

#  - 'docker run -d --name otel-collector --memory=2g --cpus=2 -p 4317:4317 -p 55680:55680 otel/opentelemetry-collector:latest'   