apiVersion: v1
kind: ConfigMap
metadata:
  name: grafana-datasources
  namespace: monitoring
data:
  datasources.yaml: |
    apiVersion: 1
    datasources:
      - name: Prometheus
        type: prometheus
        access: proxy
        url: http://10.0.2.15:30900
        isDefault: true
      - name: Loki
        type: loki
        access: proxy
        url: http://loki-loki-distributed-query-frontend.monitoring:3100
        isDefault: false

---
apiVersion: v1
kind: ConfigMap
metadata:
  name: grafana-dashboards
  namespace: monitoring
  labels:
    grafana_dashboard: "1"  
data:
  dashboards.yaml: |
    apiVersion: 1
    providers:
      - name: 'default'
        folder: ''
        type: file
        options:
          path: /etc/grafana/provisioning/dashboards
  dashboard.json: |
    {
      "uid": "my-dashboard-uid",
      "title": "My Dashboard",
      "tags": ["Mydashboard", "logs"],
      "timezone": "",
      "panels": [
        {
          "title": "My Prometheus Panel",
          "type": "graph",
          "datasource": "Prometheus",
          "targets": [
            {
              "expr": "rate(http_requests_total[5m])",
              "legendFormat": "HTTP Requests Rate",
              "refId": "A"
            },
            {
              "expr": "avg(rate(node_cpu_seconds_total{mode!=\"idle\"}[5m])) * 100",
              "legendFormat": "CPU Load (%)",
              "refId": "B"
            },
            {
              "expr": "(node_memory_MemTotal_bytes - node_memory_MemAvailable_bytes) / node_memory_MemTotal_bytes * 100",
              "legendFormat": "Memory Usage (%)",
              "refId": "C"
            }
          ],
          "gridPos": {
            "x": 0,
            "y": 0,
            "w": 24,
            "h": 8
          }
        }
      ]
    }