apiVersion: v1
kind: ConfigMap
metadata:
  name: grafana-datasources
  namespace: monitoring
data:
  datasources.yaml: |
    apiVersion: 1
    datasources:
      - name: Prometheus
        type: prometheus
        access: proxy
        url: http://10.0.2.15:30900
        isDefault: true
      - name: Loki
        type: loki
        access: proxy
        url: http://loki-loki-distributed-query-frontend.monitoring:3100
        isDefault: false
      - name: Promtail
        type: loki
        access: proxy
        url: http://promtail-service.monitoring:3100
        isDefault: false
