
server:
  service:
    type: NodePort           
    nodePort: 30900          
    port: 9090               
    targetPort: 9090         


extraScrapeConfigs: |
  - job_name: 'nginx-exporter'
    honor_timestamps: true
    scrape_interval: 30s
    scrape_timeout: 10s
    metrics_path: /metrics
    scheme: http
    static_configs:
      - targets:
          - 'nginx-exporter.nginx.svc.cluster.local:9113'
