- name: Kubernetes Cluster Setup
  tags: k3scluster
  become: yes
  block:
    - name: Install K3s
      shell: curl -sfL https://get.k3s.io | sh -
      args:
        creates: /usr/local/bin/k3s

    - name: Adjust kubeconfig permissions for non-root access
      ansible.builtin.file:
        path: /etc/rancher/k3s/k3s.yaml
        mode: '0644'  

    - name: Wait for all nodes to become Ready
      command: kubectl wait --for=condition=Ready node --all --timeout=300s
      register: node_readiness
      until: node_readiness.rc == 0
      retries: 10
      delay: 10
      ignore_errors: no

    - name: Set up kubeconfig for the user
      ansible.builtin.file:
        path: /home/user/.kube
        state: directory
        owner: user
        mode: '0755'

    - name: Copy K3s kubeconfig to user directory
      ansible.builtin.copy:
        src: /etc/rancher/k3s/k3s.yaml
        dest: /home/user/.kube/config
        owner: user
        group: user
        mode: '0644'

    - name: Add KUBECONFIG to user’s environment
      ansible.builtin.lineinfile:
        path: /home/user/.bashrc
        line: 'export KUBECONFIG=/home/user/.kube/config'
        create: yes
        owner: user

    - name: Ensure rancher registries.yaml is present
      copy:
        src: files/registries.yaml
        dest: /etc/rancher/k3s/registries.yaml
        owner: root
        group: root
        mode: '0644'  
    
    - name: Restart k3s service
      service:
        name: k3s
        state: restarted
        enabled: yes

    - name: Wait for k3s service to be active
      ansible.builtin.shell: systemctl show -p ActiveState k3s | grep -q "ActiveState=active"
      register: k3s_status
      until: k3s_status.rc == 0
      retries: 10
      delay: 10
      changed_when: false

    - name: Adjust kubeconfig permissions for non-root access
      ansible.builtin.file:
        path: /etc/rancher/k3s/k3s.yaml
        mode: '0644'  

    - name: Add Rook Helm repo
      ansible.builtin.command: helm repo add rook-release https://charts.rook.io/release
      args:
          creates: ~/.helm/repository/cache/rook-release-index.yaml


