spec:
  template:
    spec:
      containers:
        - name: swagger-petstore
          env:
            - name: CORS_ALLOWED_ORIGINS
              value: "*"
            - name: CORS_ENABLED
              value: "true"
