name: CI - Setup Cluster in VM Lab

on:
  push:
    branches:
      - ansible
  pull_request:
    branches:
      - ansible

jobs:
  setup-cluster:
    runs-on: self-hosted  # Use your self-hosted runner

    steps:
      - name: Checkout code
        uses: actions/checkout@v3
        with:
          submodules: recursive 

      - name: Prepare and Start VM Lab
        id: wait_for_cluster
        run: |
          make start_lab

      - name: Wait for Cluster Setup
        run: |
          cloud_init_status=$(ssh -p 8022 user@localhost 'cloud-init status --wait' 2>&1)
          if [[ "$cloud_init_status" != "status: done" ]]; then
            echo "Cloud-init failed or did not complete successfully."
            echo "Details: $cloud_init_status"
            exit 1
          fi
          echo "Cloud-init completed successfully!"

      - name: Display Cloud-Init Logs on Failure
        if: failure()
        run: |
          ssh -p 8022 user@localhost 'tail -n 50 /var/log/cloud-init.log'
          
      - name: Verify Cluster Deployment
        if: sucess()
        run: |
          ssh -p 8022 user@localhost "bash -s" < ./full-test.sh
